### ISSUE TITLE
Not invited as contributor 

### ISSUE THREAD

**Issue by creaturenex** [carmenkolohe/CodeSchoolQA#1]
**Issue:**
I was not invited to contribute to this repo.

**Correction:**
Add me as contributor:

![BabyDumpsters](https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/opener-1563996884.png?crop=0.900xw:0.901xh;0.0459xw,0.00341xh&resize=980:*)

**Comment by carmenkolohe** [comment]
You are the best @creaturenex ! Will correct immediately!! 
![fulldumpter](https://user-images.githubusercontent.com/69023218/126568716-b9abfbea-6487-4137-a3c4-ae227e414f1a.jpeg)
