### ISSUE TITLE
Planning MVP Scope

### ISSUE THREAD

**Issue by jendevelops** [carmenkolohe/CodeSchoolQA#2]
# Motivations
- for people who can't make it to the stream that wants to ask questions
- have the streamers be able to answer questions, and have a timestamp for the VOD where the answer is
- keep stream organized
- have people to be able to learn Next.js and Sass and keep the learning train going

# Technologies
## Backend
- Firestore Realtime Database 
- Some alternatives
  - Planet Scale
  - Firebase
  
 # To Do
## Design
 - [x] MVP Wireframe
 - [ ] Data schema/ DB design
 - [ ] Solidify Technologies to be used
 
 ## Project Planning
  - [x] Update Readme with new Planning docs
  - [x] Update Contribution + PR Process dock
  - [ ] Write tickets

**Comment by carmenkolohe** [comment]
Wireframe for v0.1 is in Miro! Readme update is ready for a PR 🥳
