### ISSUE TITLE
Feature -  Add GitHub About section

### ISSUE THREAD

**Issue by danitcodes** [carmenkolohe/CodeSchoolQA#7]
Hi, frens! Just a little detail, and I know y'all are adding a bunch of stuff before Hacktober. But if this isn't yet on your radar, it'd be helpful to add a sentence or two about what the project is in this about section. Also would be a great idea to tag the different languages/frameworks you're planning on working with (nextjs, sass, etc.)

Also, if you want to add me as an admin, would be mooooore than happy to help out where I can, and do some of this myself! :) Maybe adding @codingmoore or @thejonanshow would be a thing, too? All up to you though! <3 

![Screen Shot 2021-09-18 at 2 30 57 PM](https://user-images.githubusercontent.com/71739178/133909031-efde15d1-f84e-4b2f-9861-cc516886fb77.png)

**Comment by carmenkolohe** [comment]
Thank you @danitcodes I appreciate your thoughts and input! 

To clarify, are you referring to the README or where were you thinking of adding this information? 

I can 100% add you as an admin, thank you so much 💕   I have asked both of our friends if they would like to be admins a while ago but, if they change their minds I would be more than happy to add them as well.

**Comment by danitcodes** [comment]
Knew I should've included a screenshot! Sorry about that, @carmenkolohe!
[image: Screen Shot 2021-09-22 at 4.33.27 PM.png]

And yay adding me as admin! <3

Cheers,
Danielle Thompson
She/Her
Software Developer
GitHub <http://github.com/danitcodes> | LinkedIn
<https://www.linkedin.com/in/danielle-thompson74/>

**Comment by carmenkolohe** [comment]
Pictures always makes things better😸

@danitcodes the screenshot you send did not work, if it's easy send it to me on one of our other platforms and I can take a look at it there

yay friends!  🥳

**Comment by danitcodes** [comment]
That's what I get for emailing, instead of doing this in GitHub 🙃 

![Screen Shot 2021-09-22 at 4 33 27 PM](https://user-images.githubusercontent.com/71739178/134437637-179254aa-aa87-4ba4-bd95-ce9da9d5dda9.png)
