### ISSUE TITLE
Documentation - add @jendevelops and @creaturenex links

### ISSUE THREAD

**Issue by danitcodes** [carmenkolohe/CodeSchoolQA#8]
Especially since y'all are working on the code school QA open source project together, and since y'all are regular fixtures on The Jonan Show, @creaturenex and @jendevelops should both be in this list. :) 

Again, if you add me as an admin, I can knock this out myself! <3

![Screen Shot 2021-09-18 at 2 35 42 PM](https://user-images.githubusercontent.com/71739178/133909133-359991a6-1407-4814-adce-51fc9a510c7f.png)

**Comment by carmenkolohe** [comment]
@danitcodes Love this! Yes, assigned to you! Thank you for your contribution!

**Comment by carmenkolohe** [comment]
Also, while you're in there, if you'd like to change the email that is currently on the README in the 💌  Contact section to the one you created please feel free to. I haven't gotten around to it yet but, it's on my list of TODOs
